# Generated by Django 5.1.3 on 2024-12-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CherryDineApp", "0004_orderitem_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="price",
            new_name="item_price",
        ),
    ]
