# Generated by Django 5.1.3 on 2024-12-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CherryDineApp", "0005_rename_price_orderitem_item_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="item_price",
        ),
    ]
