# Generated by Django 5.1.3 on 2024-12-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CherryDineApp", "0006_remove_orderitem_item_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="menu_item",
        ),
    ]
