# Generated by Django 5.1.3 on 2024-12-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CherryDineApp", "0007_remove_review_menu_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "В обработке"),
                    ("cancelled", "Отменён"),
                    ("ready", "Готово"),
                    ("delivered", "Доставлено"),
                ],
                default="processing",
                max_length=10,
            ),
        ),
    ]
