# Generated by Django 5.1.3 on 2024-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CherryDineApp", "0008_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_items/"),
        ),
    ]
